export enum InputTypes {
  HIDDEN = "hidden",
  TEXT = "text",
  NUMBER = "number",
  SWITCH = "switch",
  SELECT = "select",
  CHECK_LIST = "checklist",
  // SWITCH_LIST = "switchlist",
  GROUPED_SWITCH_LIST = "grouped_switchlist",
  DATE = "date",
  TEXTAREA = "textarea",
  FILE = "file",
  OTP = "otp",
  FORM = "form",
  COLOR = "color",
}

export const inputFieldComp = [
  InputTypes.GROUPED_SWITCH_LIST,
  InputTypes.TEXT,
  InputTypes.SWITCH,
  InputTypes.COLOR,
  InputTypes.OTP,
  InputTypes.SELECT,
  InputTypes.DATE,
  InputTypes.FILE,
  InputTypes.FORM,
  InputTypes.NUMBER,
  InputTypes.TEXTAREA,
  // InputTypes.SWITCH_LIST,
  InputTypes.HIDDEN,
]